# Jekyll Site settings
title: CSC 207.02 2019S
baseurl: /~rebelsky/Courses/CSC207/2019S/02
url: http://www.cs.grinnell.edu/~rebelsky/Courses/CSC207/2019S/02

# Set the theme color. Options are blue, green, red, orange, purple, and gray
color: purple

instructor: Samuel A. Rebelsky

instructor_title: Professor Rebelsky

instructor_homepage: https://www.cs.grinnell.edu/~rebelsky

instructor_email: rebelsky@grinnell.edu

meeting_times: MWF 1:00&ndash;2:20 (section 02)

section_number: "02"

office_hours:
  - 9:00-11:00 Tu, 9:00-10:00 Th, 1:00-3:00 Th (_tentative_)

mentors:
  - Anh Thu Pham (section 01)
  - Shuyi Qi (section 02)

mentor_sessions:
  - 7-8 p.m. Sundays in Science 3813

tutors:
  - Su from 1&ndash;3pm in Noyce 3813
  - Su, M, T, W, Th from 7&ndash;10pm in Noyce 3813

grader_email: "csc207-01-grader@grinnell.edu"

all_work_deadline: 5:00pm on Friday, 17 May 2019
final_exam_time: TBD

copyright: |
  Copyright &copy; Samuel A. Rebelsky.  Selected materials are copyright by
  other members of the CS department and are used with permission.

copyright_message: |
  Unless specified otherwise elsewhere on the page, this work is
  licensed under a Creative Commons Attribution 4.0 International
  License.  To view a copy of this license, visit
  <http://creativecommons.org/licenses/by/4.0/>.

java_api: https://docs.oracle.com/en/java/javase/11/docs/api/java.base

osera: https://www.cs.grinnell.edu/~rebelsky/Courses/CSC207/osera

# Be picky about front-matter
strict_front_matter: true

# Set up collections for course content
collections:
  admin:
    output: false

  assignments:
    output: true
    permalink: /assignments/:path.html
 
  current:
    output: true;
    permalink: /current/:path.html

  eboards:
    output: true
    permalink: /eboards/:path.html

  exams:
    output: true
    permalink: /exams/:path.html

  handouts:
    output: true
    permalink: /handouts/:path.html

  labs:
    output: true
    permalink: /labs/:path.html

  links:
    output: true
    permalink: /links/:path.html

  prelim:
    output: false

  problems:
    output: false
  
  project:
    output: true
    permalink: /project/:path.html

  readings:
    output: true
    permalink: /readings/:path.html

  stuff:
    output: true
    permalink: /stuff/:path.html

  writeups:
    output: true
    permalink: /writeups/:path.html

# Default layouts
defaults:
  - scope:
      path: ""
    values:
      layout: default
  
  - scope:
      path: ""
      type: assignments
    values:
      link: false
      layout: assigned
      collaboration: |
        You must work with your assigned partner(s) on this assignment. You may
        discuss this assignment with anyone, provided you credit such 
        discussions when you submit the assignment.
      submitting: |
        Share your GitHub repo with csc207-grader. Then send
        an email to <{{ site.grader_email }}> with the address of
        your repository.  The subject of your
        email should be **[CSC207-{{ site.section_number }}] {{ page.title }}**
        and should contain your answers to all parts of the assignment. 

  - scope:
      path: ""
      type: exams
    values:
      link: false
      layout: assigned
 
  - scope:
      path: ""
      type: labs
    values:
      link: true
      section: Lab
      layout: assigned

  - scope:
      path: ""
      type: project
    values:
      link: false
      section: Project
      layout: assigned

  - scope:
      path: ""
      type: readings
    values:
      link: true
      layout: assigned

  - scope:
      path: ""
      type: writeups
    values:
      link: true
      layout: writeup

# Build settings
exclude:
  - tasks
  - README.md
  - Gemfile
  - Gemfile.lock
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    default_lang: java
    span:
      line_numbers: false
    block:
      line_numbers: false

# Plugin Settings
plugins:
  - jekyll-bootstrap-sass
  - jekyll-include-cache
   
bootstrap:
  assets: true
